version: '3.2'

services:

  smoothie_app: &app
    build:
      context: .
      args:
        requirements: requirements/development.txt
    container_name: smoothie
    environment:
      # use in code
      - DEBUG=True
      - SETTINGS_FILE=api.dev.yml
    restart: always
    volumes:
      - .:/app:delegated
    depends_on:
      - postgres
    ports:
      - 8080:8080
      - 8081:8081
    command: make adev

  postgres:
      image: postgres:10
      container_name: smoothie_postgres
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
      ports:
          - 5432:5432

  test:
    <<: *app
    container_name: smoothie_test
    ports:
      - 8082:8082
    command: make _test
